# Saving setup
algorithm: erm
phase: train
save_folder: results/

# Training dataset information
data_dir: /home/acorso/data/
n_classes: 2
train_dataset: camelyon17-train

# Parameters controlling resources
max_num_workers: 32
accelerator: gpu
devices: 1

# Training params - (Many of these are likely going to be tuned)
max_epochs: 1
lr: 0.001
train_batch_size: 512
optimizer: adam
model: densenet121
label_smoothing: 0.0

# HRE setup
val_id_dataset: camelyon17-id_val
val_ds_datasets:
  - camelyon17-val
val_ood_datasets:
  - gaussian_noise-(96x96)
test_id_dataset: camelyon17-id_test
test_ds_datasets:
  - camelyon17-test
test_ood_datasets:
  - rxrx1-id_test
val_dataset_length: 1000
val_batch_size: 1024
test_dataset_length: 10000
min_performance: 0.7
max_performance: 1.0
w_perf: 0.2
w_rob: 0.2
w_sec: 0.2
w_cal: 0.2
w_oodd: 0.2
