program: /home/acorso/Workspace/holistic-reliability-evaluation/training/train.py
method: random

metric:
  name: val_performance
  goal: maximize

early_terminate:
  type: hyperband
  min_iter: 1

parameters:
  phase:
    values: [tune]
  label_smoothing:
    values: [0.1, 0.01, 0.0]
  optimizer:
    values: [adam, sgd, rmsprop, adagrad, adamw]
  train_batch_size:
    values: [32, 64, 128, 256, 512]
  lr:
    distribution: log_uniform_values
    min: 1e-4
    max: 1e-2

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - --config
  - /home/acorso/Workspace/holistic-reliability-evaluation/training/configs/camelyon-defaults.yml
  - --phase
  - tune
