program: /home/acorso/Workspace/holistic-reliability-evaluation/holistic_reliability_evaluation/train.py
method: random

metric:
  name: val_ds_performance
  goal: maximize

early_terminate:
  type: hyperband
  min_iter: 1

parameters:
  phase:
    values: [tune]
  label_smoothing:
    values: [0.1, 0.01, 0.0]
  optimizer:
    values: [adam, sgd, adamw]
  batch_size:
    values: [32, 64, 128]
  lr:
    distribution: log_uniform_values
    min: 1e-4
    max: 1e-2
  unfreeze_k_layers:
    values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - --config
  - /home/acorso/Workspace/holistic-reliability-evaluation/configs/iwildcam-finetune.yml
  - --phase
  - tune
