# Saving setup
algorithm: erm
phase: train
save_folder: /scratch/users/acorso/results/

# Training dataset information
data_dir: /scratch/users/acorso/data/
n_classes: 1139
train_dataset: rxrx1-train
size: [256, 256]
n_channels: 3
train_transforms: []
eval_transforms: [standardize]
# These are for scaling the performance:
min_performance: 0.
max_performance: 1.0

# Parameters controlling resources
max_num_workers: 32
accelerator: gpu
devices: 1

# Training params - (Many of these are likely going to be tuned)
max_epochs: 90
lr: 0.001
train_batch_size: 32
optimizer: adam
model: resnet50
label_smoothing: 0
pretrained_weights: DEFAULT
freeze_weights: False

# HRE setup
val_id_dataset: rxrx1-id_val
val_ds_datasets:
  - rxrx1-val
  - rxrx1-id_val-corruption1_val
val_ood_datasets:
  - gaussian_noise
  - iwildcam-id_val
  - fmow-id_val
  - camelyon17-id_val
test_id_dataset: rxrx1-id_test
test_ds_datasets:
  - rxrx1-test
  - rxrx1-id_test-corruption1_test
test_ood_datasets:
  - gaussian_noise
  - iwildcam-id_test
  - fmow-id_test
  - camelyon17-id_test
val_dataset_length: 1024
val_batch_size: 1024
test_dataset_length: 1024
num_adv: 100
w_perf: 0.2
w_rob: 0.2
w_sec: 0.2
w_cal: 0.2
w_oodd: 0.2
